"""empty message

Revision ID: 0ba9ff0ee85e
Revises: 15295cda4ca0
Create Date: 2025-12-31 16:09:57.669828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba9ff0ee85e'
down_revision = '15295cda4ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blogs_title_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('blogs_title_key'), ['title'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
