"""empty message

Revision ID: 15295cda4ca0
Revises: d8b7372ca52f
Create Date: 2025-12-31 15:21:29.850018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15295cda4ca0'
down_revision = 'd8b7372ca52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
