"""empty message

Revision ID: a4d45d3fbde3
Revises: 0ba9ff0ee85e
Create Date: 2025-12-31 16:25:01.415019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d45d3fbde3'
down_revision = '0ba9ff0ee85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
