"""empty message

Revision ID: c27aea953f2e
Revises: 7db6082870c1
Create Date: 2026-01-05 18:21:35.176744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27aea953f2e'
down_revision = '7db6082870c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blogs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('likes_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('likes_blog_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('likes_blog_id_fkey'), 'blogs', ['blog_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('likes_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blogs_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
